### ISSUE TITLE
raven python client for sentry is deprecated 

### ISSUE THREAD

**Issue by adamshire123** [MITLibraries/mitlibraries.github.io#53]
raven python client for sentry integration is deprecated.

https://mitlibraries.github.io/exception_monitoring.html should be updated with new instructions for using Sentry SDK for python instead of Raven 

https://docs.sentry.io/error-reporting/quickstart/?platform=python

**Comment by JPrevost** [comment]
Likely apps needing updating (please check off once they are updated or determined to not need updates)
- [x] ebooks
- [x] oa stories
- [x] solenoid
